name: Windows Tailscale RDP

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Download and Install Tailscale
      run: |
        Invoke-WebRequest -Uri "https://pkgs.tailscale.com/stable/tailscale-setup-latest.exe" -OutFile "tailscale.exe"
        Start-Process -FilePath ".\tailscale.exe" -ArgumentList "/quiet" -Wait

    - name: Connect to Tailscale
      run: |
        & "C:\Program Files\Tailscale\tailscale-ipn.exe" --noninteractive
        & "C:\Program Files\Tailscale\tailscale.exe" up --authkey=${{ secrets.TAILSCALE_AUTHKEY }}

    - name: Enable Remote Desktop & Keep Alive
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Start-Sleep -Seconds 7200
